{{- $fullName := include "api.fullname" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $fullName }}-nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-proxy-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
        {{- range $index, $endpoint := .Values.endpoints }}
        - name: {{ $fullName }}-{{ .name }}
          {{- if .securityContext }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .image.repository }}:{{ .image.tag | default "latest" }}"
          imagePullPolicy: {{ .image.pullPolicy | default "Always" }}
          ports:
            - containerPort: {{ .port | default "80" }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
          env:
            - name: API_PORT 
              value: "{{ add $index 15170 }}"
          {{- if .disableRedis }} {{ else }}
            - name: REDIS_HOST
              value: "localhost"
            - name: REDIS_PORT
              value: "{{ add $index 14620 }}"
            - name: REDIS_DB
              value: "0"
          {{- end }}
          {{- if .env }}
            {{- toYaml .env | nindent 12 }}
          {{- end }}
          {{- if .command }}
          command:
            {{- toYaml .command | nindent 12  }}
          {{- end }}
          {{- if .args }}
          args:
            {{- toYaml .args | nindent 12  }}
          {{- end }}
      {{- if .disableRedis }} {{ else }}
        - name: {{ $fullName }}-{{ .name }}-redis
          image: "redis:7"
          ports:
            - containerPort: {{ add $index 14620 }}
          env:
            - name: MASTER
              value: "true"
          command: ["redis-server"]
          args: ["-p", {{ add $index 14620 | quote }}]
          volumes:
            - mountPath: /redis-master-data
              name: {{ $fullName }}-{{ .name }}-redis-data
      {{- end}}
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: nginx-proxy-config-volume
          configMap:
            name: {{ $fullName }}-nginx-conf
      {{- range $index, $endpoint := .Values.endpoints }}
      {{- if .disableRedis }} {{ else }}
        - name: {{ $fullName }}-{{ .name }}-redis-data
          emptyDir: {}
      {{- end }}
      {{- end }}
