{{- $fullName := include "api.fullname" . -}}
{{- $apiPortRange := 15170 -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-nginx-conf

data:
  nginx.conf: |-
    user nginx;
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        {{- range $index, $endpoint := .Values.endpoints }}
        {{- $apiPort := (add $apiPortRange $index) }}
        location /{{ .path }}/ {
          client_max_body_size 0;
          proxy_pass http://127.0.0.1:{{ $apiPort | default "80" }};
        }
        {{- end }}
      }
    }
