{{- $fullName := include "api.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-nginx-conf

data:
  nginx.conf: |-
    user nginx;
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        {{ range $.Values.endpoints }}
        location /{{ .path }}/ {
          proxy_pass http://127.0.0.1:{{ .port | default "80" }};
        }
        {{- end }}
      }
    }
