{{- $fullName := include "api.fullname" . -}}
{{- $labels := include "api.labels" . -}}
{{- $selectorLabels:= include "api.selectorLabels" . -}}

{{- range $.Values.endpoints }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    {{- $labels }}
spec:
  type: {{ (.service).type | default "ClusterIp" }}
  ports:
    - port: {{ .port | default "80" }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- $selectorLabels }}
{{- end }}
